@startuml principal
skinparam sequenceParticipant underline
mainframe sd 5 Importar actualización de vinos de bodega
    actor ":Administrador de Bonvino" as AB #LightBlue
    boundary ":PantAdmVinos" as pantalla #LightBlue
    control ":GestorAdmVinos" as controlador #LightBlue
    entity ":Bodega" as bodegas #orange
    entity "seleccionado:Bodega" as objeto #LightBlue
    actor ":Sistema de bodega" as sisBod #LightBlue

    activate AB
    AB -> pantalla :  opcionImportarVinosBodega()
    activate pantalla

    pantalla -> pantalla : habilitarVentana()
    activate pantalla
    deactivate pantalla

    pantalla -> controlador : To control
    activate controlador
    AB -> objeto : To database

@enduml