@startuml principal
skinparam sequenceParticipant underline
mainframe sd 5 Importar actualización de vinos de bodega
    actor ":Administrador de Bonvino" as AB #LightBlue
    boundary ":PantImpVinos" as pantalla #LightBlue
    control ":GestorImpVinos" as controlador #LightBlue
    entity ":Bodega" as bodegas #Orange
    entity "seleccionado:Bodega" as bodega #LightBlue
    boundary ":IntApiBodega" as interfaz #LightBlue
    actor ":ApiBodega" as api #LightBlue
    entity ":Vino" as vinos #Orange
    entity "seleccionado:Vino" as vino #LightBlue
    entity ":enofilo" as enofilo #LightBlue
    entity ":seguido" as seguido #LightBlue

    activate AB #LightBlue

        AB -> pantalla ++ #LightBlue :  opcionImportarVinosBodega()

            pantalla -> pantalla ++ #LightBlue : habilitarVentana()

            deactivate pantalla 

            pantalla -> controlador ++ #LightBlue : obtenerBodegasActualizaciones()


                controlador -> controlador ++ #LightBlue : buscarBodegas()

                deactivate controlador

                controlador -> bodegas ++ #Orange : *getPeriodoActualizacion()
                deactivate bodegas
                controlador -> bodegas ++ #Orange : *getNombre()
                deactivate bodegas

                controlador -> pantalla ++ #LightBlue : pedirSeleccionBodega()
                deactivate pantalla
            deactivate controlador
        deactivate pantalla
    
        
        AB -> pantalla ++ #LightBlue : tomarSeleccionBodega()
            pantalla -> controlador ++ #LightBlue : tomarSeleccionBodega()
            loop Mientras haya bodegas seleccionadas    
                controlador -> controlador ++ #LightBlue : buscarActualizacionesBodega()
                deactivate controlador

                controlador -> interfaz ++ #LightBlue : buscarActualizacionesBodega()

                    interfaz -> api ++ #LightBlue : getAñada()
                        deactivate api
                        interfaz -> api ++ #LightBlue : getImagenEtiqueta()
                        deactivate api
                        interfaz -> api ++ #LightBlue : getNombre()
                        deactivate api
                        interfaz -> api ++ #LightBlue : getNotaDeCataBodega()
                        deactivate api
                        interfaz -> api ++ #LightBlue : getPrecioARS()
                        deactivate api
                    deactivate interfaz
                

                loop Mientras haya vinos para cargar
                    controlador -> bodega ++ #LightBlue : extisteVino()       
                        bodega -> vinos ++ #Orange : * esVinoNombre()
                        deactivate vinos
                        bodega -> vino ++ #LightBlue : setAñada()
                        deactivate vino
                        bodega -> vino ++ #LightBlue : setImagenEtiqueta()
                        deactivate vino
                        bodega -> vino ++ #LightBlue : setNotaCataBodega()
                        deactivate vino
                        bodega -> vino ++ #LightBlue : setPrecioARS()
                        deactivate vino
                    deactivate bodega

                    controlador -> bodega ++ #LightBlue : crearVino()
                        entity "nuevo:Vino" as nvino
                        bodega -> nvino ** : new()
                        
                    deactivate bodega
                end

                controlador -> pantalla : mostrarListadoVinosImportados()
                controlador -> controlador ++ #LightBlue : enviarNotificaciones()
                deactivate controlador
                controlador -> enofilo ++ #LightBlue : tomarEnofilosBodega()
                    enofilo -> seguido ++ #LightBlue : sosDeBodega()
                        seguido -> seguido ++ #LightBlue : enviarNotificacion()
                        deactivate seguido
                    deactivate seguido
                deactivate enofilo
            end
                controlador -> controlador ++ #LightBlue : finCU()
                deactivate controlador                
            deactivate controlador
        deactivate pantalla
    deactivate AB
@enduml