@startuml principal
skinparam sequenceParticipant underline
mainframe sd 5 Importar actualización de vinos de bodega
    actor ":Administrador de Bonvino" as AB #LightBlue
    boundary ":PantImpVinos" as pantalla #LightBlue
    control ":GestorImpVinos" as controlador #LightBlue
    entity ":Bodega" as bodegas #Orange
    entity "seleccionado:Bodega" as bodega #LightBlue
    actor ":Sistema de bodega" as api #LightBlue
    entity ":Vino" as vinos #Orange

    activate AB #LightBlue

        AB -> pantalla ++ #LightBlue :  opcionImportarVinosBodega()

            pantalla -> pantalla ++ #LightBlue : habilitarVentana()

            deactivate pantalla 

            pantalla -> controlador ++ #LightBlue : importarActualizacionVinosBodega()


                controlador -> controlador ++ #LightBlue : buscarBodegas()

                deactivate controlador

                controlador -> bodegas ++ #Orange : *getPeriodoActualizacion()
                deactivate bodegas
                controlador -> bodegas ++ #Orange : *getNombre()
                deactivate bodegas

                controlador -> pantalla ++ #LightBlue : pedirSeleccionBodega()
                deactivate pantalla
            deactivate controlador
        deactivate pantalla
    
        AB -> pantalla ++ #LightBlue : tomarSeleccionBodega()
            pantalla -> controlador ++ #LightBlue : tomarSeleccionBodega()
                controlador -> controlador ++ #LightBlue : buscarActualizacionesBodega()
                deactivate controlador

                controlador -> bodega ++ #LightBlue : buscarActualizacionesBodega()
                    bodega -> api ++ #LightBlue : getVinos()
                    deactivate api
                deactivate bodega

                loop Mientras haya vinos para cargar
                    controlador -> vinos ++ #Orange : * extisteVino()
                    deactivate vinos

                    controlador -> bodega ++ #LightBlue : crearVino()
                        entity "nuevo:Vino" as nvino
                        bodega -> nvino ** : new()
                        
                    deactivate bodega
                end

                controlador -> pantalla : mostrarListadoVinosImportados()

                controlador -> controlador ++ #LightBlue : finCU()
                deactivate controlador                
            deactivate controlador
        deactivate pantalla
    deactivate AB
@enduml