@startuml clases

class PantImpVinos <<boundary>> {
    - listaBodegas
    - lblBodegas
    - bodegaElegida
    + opcionImportarVinosBodega()
    + habilitarVentana()
    + pedirSeleccionBodega()
    + tomarSeleccionBodega()
    + mostrarListadoVinosImportados()
}

class GestorImpVinos <<control>> {
    - bodegas
    - bodegaElegida
    + importarActualizacionVinosBodega()
    + buscarBodegas()
    + tomarSeleccionBodega()
    + buscarActualizacionesBodega()
    + finCU()
}

class Bodega <<entity>> {
    - coordenadasUbicacion[]
    - descripcion
    - historia
    - nombre
    - periodoActualizacion
    + contarReseñas()
    + mostrarTodosVinos()
    + getNombre()
    + getPeriodoActualizacion()
    + buscarActualizacionesBodega()
    + crearVino()
}

class Vino <<entity>> {
    - añada
    - imagenEtiqueta
    - nombre
    - notaDeCataBodega
    - precioARS
    + calcularRanking()
    + compararEtiqueta()
    + esDeBodega()
    + esDeRegionVitivinicola()
    + extisteVino()
}

class Siguiendo <<entity>> {
    - fechaFin
    - fechaInicio
    + sosDeAmigo()
    + sosDeBodega()
    + sosDeSomelier()
}

class Enofilo <<entity>> {
    - apellido
    - imagenPerfil
    - nombre
    + mostrarAmigosSeguidos()
    + mostrarColeccionFavoritos()
}

PantImpVinos ..> GestorImpVinos
PantImpVinos <.. GestorImpVinos
GestorImpVinos .> Bodega
Siguiendo --> "0..1" Bodega

Enofilo --> "0..*" Vino
Siguiendo -> "0..1" Enofilo
Bodega "1" <- Vino
@enduml
